//! What damages the map (Y11S3): the damage ids of the records of a damage
//! list (see [`crate::world`]) and the assets of breach devices.
//!
//! Generated by `SP\D\gen_tables.py` (SP = C:\Users\Mark\AppData\Local\Temp\claude\D--Development-replay-analyzer\
//! 4552b641-01d1-48d9-bf84-1627e02cf63c\scratchpad)
//! from `causes.json` and `device_assets.json` there, which were built
//! from 184 rounds. Do not edit by hand.

use Category::*;

/// What kind of thing a cause is.
#[derive(Clone, Copy, Debug, PartialEq, Eq, serde::Serialize)]
#[serde(rename_all = "camelCase")]
pub enum Category {
    Melee,
    Ability,
    Reinforcement,
    HardBreach,
    SoftBreach,
    Explosive,
    Placement,
    Physics,
    Environment,
    Unknown,
}

/// What a damage id stands for.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) struct Cause {
    pub id: u64,
    pub name: &'static str,
    pub category: Category,
    /// It removes material from a soft wall or floor. From how the game
    /// behaves, not from a field.
    pub holes: bool,
    /// It opens reinforcements: their intact flag was seen cleared after
    /// it.
    pub hard: bool,
    /// What the id stands for was worked out by exclusion or behaviour;
    /// the others were confirmed by the entity or the player that did it.
    pub inferred: bool,
}

const fn c(
    id: u64,
    name: &'static str,
    category: Category,
    holes: bool,
    hard: bool,
    inferred: bool,
) -> Cause {
    Cause {
        id,
        name,
        category,
        holes,
        hard,
        inferred,
    }
}

/// Every damage id that is not a bullet's, with the evidence for it.
#[rustfmt::skip]
pub(crate) const CAUSES: &[Cause] = &[
    // confirmed
    c(34118943362, "Melee", Melee, true, false, false),
    // confirmed (26 by Sledge; rest preset map damage)
    c(34118943366, "Sledge hammer", Ability, true, false, false),
    // confirmed (instigator = reinforcing player, lands on both wall faces and on the reinforcement entity)
    c(42593091656, "Wall reinforcement anchors", Reinforcement, false, false, false),
    // confirmed (117/117 within 0.1 s of a hatch reinforcement going live; body 0; the hatch object then reports destroyed)
    c(364196079763, "Hatch reinforcement placed", Reinforcement, false, false, false),
    // confirmed (ticks every 0.58 s by the placing player before the detonation)
    c(293850527318, "Hard Breach Charge fuse", HardBreach, false, false, false),
    // confirmed
    c(261358999180, "Hard Breach Charge", HardBreach, true, true, false),
    // confirmed (6 impacts: the hexagon)
    c(285432852752, "Hard Breach Charge", HardBreach, true, true, false),
    // confirmed (on walls)
    c(39838030204, "Exothermic Charge", HardBreach, true, true, false),
    // confirmed (on hatches and floors)
    c(34118943338, "Exothermic Charge", HardBreach, true, true, false),
    // confirmed
    c(244764702446, "S.E.L.M.A. Aqua Breacher", HardBreach, true, true, false),
    // inferred (by Ace's body, 2 impacts, ~0.8 s before each stage goes live)
    c(281437417201, "S.E.L.M.A. attaching", HardBreach, false, false, true),
    // inferred (7 records by Ace on reinforcements, each clears the intact flag)
    c(271744976709, "S.E.L.M.A. Aqua Breacher", HardBreach, true, true, true),
    // confirmed (by Hibana's body, one impact per pellet at the pellet's position)
    c(41850534886, "X-KAIROS", HardBreach, true, true, false),
    // confirmed (Maverick, on reinforcements only)
    c(171524950208, "Breaching Torch", HardBreach, true, true, false),
    // confirmed (Maverick, on map objects)
    c(155037197079, "Breaching Torch", HardBreach, true, false, false),
    // confirmed (Maverick, on map objects, several impacts)
    c(137413294363, "Breaching Torch", HardBreach, true, false, false),
    // confirmed (on walls and barricades)
    c(39838027076, "Breach Charge", SoftBreach, true, false, false),
    // confirmed (on floors and hatches)
    c(34118943319, "Breach Charge", SoftBreach, true, false, false),
    // confirmed (Ash)
    c(34118943328, "Breaching Round", SoftBreach, true, false, false),
    // confirmed (Zofia)
    c(71127325873, "KS79 Lifeline impact grenade", SoftBreach, true, false, false),
    // confirmed
    c(44923900670, "Impact Grenade", Explosive, true, false, false),
    // confirmed (also explosive map props, instigator = the map object)
    c(34118943342, "Frag Grenade", Explosive, true, false, false),
    // confirmed (also Flores' RCE-Ratero, asset 319577330914)
    c(34118943318, "Nitro Cell", Explosive, true, false, false),
    // inferred (nitro, frag, impact, KS79, SELMA; 1-5 impacts)
    c(34118943343, "Explosion (secondary record)", Explosive, true, false, true),
    // confirmed
    c(34118943335, "Cluster Charge puck / Entry Denial Device", Explosive, true, false, false),
    // confirmed (Fuze)
    c(37904891070, "Cluster Charge drilling", Ability, true, false, false),
    // confirmed (Kali)
    c(233068073004, "LV Explosive Lance", SoftBreach, true, false, false),
    // inferred (by Kali's body)
    c(240613129973, "LV Explosive Lance impact", Ability, false, false, true),
    // confirmed
    c(319015720594, "Gonne-6", SoftBreach, true, false, false),
    // confirmed (Ram)
    c(397807658701, "BU-GI Auto-Breacher", SoftBreach, true, false, false),
    // confirmed (Thorn)
    c(375597155543, "Razorbloom Shell", Explosive, true, false, false),
    // inferred
    c(376710164277, "Gadget attaching (Razorbloom / Kiba)", Placement, false, false, true),
    // inferred (entity asset 375382544571, appears with Azami's ability use)
    c(383042342305, "Kiba Barrier", Ability, false, false, true),
    // confirmed (Goyo)
    c(361809386170, "Volcan Canister", Explosive, true, false, false),
    // confirmed (Mira; clears the intact flag of reinforcements 20 times)
    c(43879409715, "Black Mirror", Ability, true, true, false),
    // confirmed (150 by Aruni; 3 by Skopos)
    c(286324175220, "Aruni punch", Ability, true, false, false),
    // inferred (Blackbeard, at his ability use)
    c(412054322007, "H.U.L.L. shield breach", Ability, true, false, true),
    // inferred (Amaru only)
    c(237223442548, "Garra Hook", Ability, true, false, true),
    // inferred (Oryx only)
    c(243052504389, "Remah Dash", Ability, true, false, true),
    // inferred (Gridlock only)
    c(185462835935, "Trax Stingers", Placement, false, false, true),
    // not identified
    c(169100595571, "unknown (Vigil)", Unknown, false, false, true),
    // not identified
    c(170438669070, "unknown (Vigil, Clash)", Unknown, false, false, true),
    // inferred (Zero only)
    c(299415096054, "ARGUS camera", Placement, false, false, true),
    // not identified
    c(367868911965, "unknown (Osa)", Unknown, false, false, true),
    // inferred (Grim hive, Fenrir mine, Zero, Kali, Amaru; destroys small props)
    c(239911110393, "Launched gadget landing", Placement, false, false, true),
    // confirmed
    c(98603498106, "Claymore", Explosive, true, false, false),
    // confirmed (stun grenade, KS79 concussion, Grzmot mine; breaks props, not walls)
    c(65865554768, "Concussion / stun blast", Explosive, false, false, false),
    // inferred (instigator within 0.8 m, at gadget use times)
    c(272608252682, "Gadget placed on surface", Placement, false, false, true),
    // inferred (instigator player far away, 85% attackers, several records per frame)
    c(245399005534, "Drone or thrown gadget collision", Physics, false, false, true),
    // inferred (instigator is an entity with no create message; w = 0, part has the high bit)
    c(41850676485, "Physics collision (debris, props)", Physics, false, false, true),
    // not identified
    c(41850758018, "unknown (no shot; mostly defenders)", Unknown, false, false, true),
    // not identified
    c(41850758023, "unknown (no shot; on reinforcements)", Unknown, false, false, true),
    // not identified (9 records; instigator 0.15 m away: a landing?)
    c(191201204029, "unknown (player on the spot, floor)", Unknown, false, false, true),
    // inferred (instigator = the object itself; agent E)
    c(417576480429, "Environment object (self)", Environment, false, false, true),
    // inferred (instigator = the object itself; these objects later instigate 34118943342 explosions)
    c(417217030129, "Environment object (self)", Environment, false, false, true),
];

/// The cause a damage id stands for.
pub(crate) fn cause(id: u64) -> Option<&'static Cause> {
    CAUSES.iter().find(|c| c.id == id)
}

/// A breach device a player places.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) enum Device {
    HardBreachCharge,
    ExothermicCharge,
    Selma,
    BreachCharge,
}

impl Device {
    pub(crate) fn name(self) -> &'static str {
        match self {
            Device::HardBreachCharge => "Hard Breach Charge",
            Device::ExothermicCharge => "Exothermic Charge",
            Device::Selma => "S.E.L.M.A. Aqua Breacher",
            Device::BreachCharge => "Breach Charge",
        }
    }

    /// The device a loadout names so.
    pub(crate) fn named(name: &str) -> Option<Device> {
        [
            Device::HardBreachCharge,
            Device::ExothermicCharge,
            Device::BreachCharge,
        ]
        .into_iter()
        .find(|d| d.name() == name)
    }
}

/// The assets of breach devices seen detonating; a skin has its own asset.
#[rustfmt::skip]
pub(crate) const DEVICES: &[(u64, Device)] = &[
    (238373640059, Device::BreachCharge),
    (238373640266, Device::BreachCharge),
    (238373640938, Device::BreachCharge),
    (238373641115, Device::BreachCharge),
    (238373641845, Device::BreachCharge),
    (238373642367, Device::BreachCharge),
    (238373642425, Device::ExothermicCharge),
    (287579301765, Device::HardBreachCharge),
    (287579301767, Device::HardBreachCharge),
    (287579301769, Device::HardBreachCharge),
    (287579301773, Device::HardBreachCharge),
    (293250775711, Device::HardBreachCharge),
    (303265345945, Device::HardBreachCharge),
    (314025151504, Device::HardBreachCharge),
    (382578759427, Device::HardBreachCharge),
    (388352500293, Device::Selma),
    (395970902272, Device::HardBreachCharge),
    (402481160951, Device::HardBreachCharge),
    (413521661629, Device::BreachCharge),
    (415607959581, Device::HardBreachCharge),
    (442272916671, Device::BreachCharge),
    (456325317159, Device::BreachCharge),
];

/// The breach device an asset is.
pub(crate) fn device(asset: u64) -> Option<Device> {
    DEVICES.iter().find(|d| d.0 == asset).map(|d| d.1)
}
